<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EverLogger.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="RJCP.SerialPortStream" Version="3.0.1" />
  </ItemGroup>
</Project>
